arch: ResNet18
aug: true
batch_size: 256
ckpt: ''
color_dist_s: 0.5
config_file: null
data: cifar
dist: dp
dist_address: '127.0.0.1:1235'
eval_freq: 4800
head: PN
iters: 48000
log_freq: 48
lr: 4.0
lr_schedule: warmup-anneal
multiplier: 10
n_supp: 5
n_query: 5
name: 'pn_cifar10_exp'
node_rank: 0
opt: lars
problem: sim-clr
root: 'none'
save_freq: 12000
scale_lower: 0.08
seed: -1
sync_bn: true
temperature: 0.5
tmp: false
verbose: true
warmup: 0.01
weight_decay: 1.0e-06
workers: 2
world_size: 1